# Generated by Django 4.2.10 on 2024-03-21 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customuser_profile_picture_customuser_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 3, 21, 11, 13, 49, 622470, tzinfo=datetime.timezone.utc))),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_message', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
